$ANSIBLE_VAULT;1.1;AES256
64653934653538373665373636623532366264386263613061386562363365336166643034383130
3466333831613236353665613664353933356432613263310a313736323633663138303362643463
37313033373835623338303165373338393335626333636561613063326634383032363032373733
3933316332343333360a616439653832636639623839373865643663393135366139303365373135
63326431666166663132613734323231666666323032356234656364386438383237333131316230
32353761353637366238663563396130653663343330333130303235633937316331316638616333
65613162363163396231303731386330666632396134313131666434396364643836663362323830
65613365626531313534613065353037383764303539303961383939373034366630643037306161
38306536616665346539363063663665663032323335343635623931333938633265
